### PR TITLE
In the case I have selected a folder in cloud code, new files should go to that folder

### PR DESCRIPTION
**Pull request by fn-faisal**
https://www.pivotaltracker.com/story/show/178977843

### CODE REVIEW

**Review by davimacedo — COMMENTED** [review]
@fn-faisal thanks for the PR. What happens if I select a subfolder?

**Comment by fn-faisal** [comment]
> @fn-faisal thanks for the PR. What happens if I select a subfolder?

The code is only for the main folders. To make it upload to subfolders I'd have to update the logic for this.

**Comment by davimacedo** [comment]
You can right click a folder and click on create to create a new subfolder. BTW, could you please also change this text "Create" to "Create Folder" ?

**Comment by davimacedo** [comment]
@fn-faisal could you please fix the conflicts in here?

**Pull request merged**
