### PR TITLE
Create a new file for cloud code.

### PR DESCRIPTION
**Pull request by fn-faisal**

### CODE REVIEW

**Review by davimacedo — APPROVED** [review]

**Comment by davimacedo** [comment]
@fn-faisal could you please fix the conflicts?

**Comment by fn-faisal** [comment]
I have fixed the merge conflicts.

**Review by davimacedo — APPROVED** [review]

**Comment by davimacedo** [comment]
@fn-faisal could you please resolve the conflicts in here?

**Comment by fn-faisal** [comment]
I have fixed the conflicts

**Pull request merged**
